# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: "list all available tasks"
    cmds:
      - task --list-all
    silent: true

  start:
    desc: "start all the running docker containers (stopping them first if necessary)"
    cmds:
      - task: stop
      - docker-compose up -d
      - task: status

  stop:
    desc: "stop all the running docker containers"
    cmds:
      - docker-compose down

  status:
    desc: "current status of docker containers"
    cmds:
      - docker-compose ps
