# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  up:
    desc: "docker-compose up"
    cmds:
      - docker-compose down
      - docker-compose up -d
      - task: status

  status:
    cmds:
      - docker-compose ps
